site_name: HyperA Documentation
site_description: Documentation for the HyperA codebase understanding system
repo_url: https://github.com/JtPerez-Acle/hypera
repo_name: JtPerez-Acle/hypera

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - Installation: user-guide/installation.md
    - Configuration: user-guide/configuration.md
  - Developer Guide:
    - Contributing: CONTRIBUTING.md
    - Development Plan: DEVELOPMENT_PLAN.md
    - Test Coverage: TEST_COVERAGE.md
    - Changelog: CHANGELOG.md
  - API Reference:
    - Retrieval:
      - Gemini Integration: api/retrieval/gemini.md
      - Metrics: api/retrieval/metrics.md
      - Types: api/retrieval/types.md
    - Vector Store:
      - Schema: api/vector_store/schema.md
      - Embeddings: api/vector_store/embeddings.md
  - About:
    - Project Status: about/status.md
    - License: about/license.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JtPerez-Acle/hypera
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hypera/
